def trans(map, dna):
    result = "";
    for n in dna:
        if n in map:
            result += map[n];
        else:
            result += n;
    return result;

def transRna(dna):
    return trans({'T': 'U'}, dna);


dna = "GTGCATGGTAATAGGGTAGCCTAGTGCTGGGAATCGATGGGAGCCGGCCTTTGCAGTCCCACCGCAAGAATAGAGCCTGATCGATCGGGTCCGGGTGGTGCTGTTACATCTACCACCGTAGGGCATCAGGGGACGTAACTCCTAAAGCTTATAGGAACATATACCTTATTTTTCATTTGTGCGCCTTCAAACATCAGTGTTTGCTTTTAATGCCCCCAACACACCACAATCCTTGAGAATAGTCATCGCATGAGTGACCTCTAAGTTTTTTTTACGTTTGCAGAGGCACAGTAATCTGTGCCGCTTTGGGGTAATTACGTGCACCCATAGCAGGCGCGATGATGCTAGTCCGCAGAAAAGACGAGAGGGCAATGCCCTACATGTTATACCTGCCAGCACCTGTTATTGGCTTCTACACTACTTTCCGTCGAATTGTATCGTCAGTACCGAGGCAGCACCAAGGCGGTGCTAAAAGTAACCCGCAGGGCGACTCTGGTGGGACTATTTAAATGTTACTAGCGCCGAGGTAGTAGGCTCGCGCAGGTTGTTGGTGACAGCGTAGTAATGGTTCGAAGATAACAAACATGGGTTGTCGTGTAATGGAGCAGATTCTATATGCGGAAAATGACAATGACTGTTGTATTAGTTAGTTTCGTAGAGGCTGCCCGATACCGCGAACCTTGAGAGCTCGTCTCCGGTATACGATCGTATATATACGATTTCACGACAGGCTATTCAGATGTTACTAATCCTGGGTTAAGATGGTGACGCATTCGGAAATATCCCATTGTGGAGGAGCACTTGCGATGGAGTGAGTACATGCTCTCAACTGTCTCTTTCGACCGGACACCGGGTACCGACCCGACTCCAAGCGACCATAAGTCGAATTACCTCCGAATTCAAGGGAACGGTC";
print transRna(dna) 
